// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl6PIhPLKbJ437WADmHc44Z7nncmKGo2M',
    appId: '1:1007172590075:web:8c1a24e2b55699a73ad35e',
    messagingSenderId: '1007172590075',
    projectId: 'jamiiclubapp',
    authDomain: 'jamiiclubapp.firebaseapp.com',
    storageBucket: 'jamiiclubapp.firebasestorage.app',
    measurementId: 'G-82NRCLX50H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCshZcbuEcTWGI9Xx3PGmyLBAEpgxQA4g8',
    appId: '1:1007172590075:android:848327ceb3dfa03c3ad35e',
    messagingSenderId: '1007172590075',
    projectId: 'jamiiclubapp',
    storageBucket: 'jamiiclubapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyeCVyyr-xm6q5YGFa6dzev6NEDQHRR5M',
    appId: '1:1007172590075:ios:aa7f2648869dd5f03ad35e',
    messagingSenderId: '1007172590075',
    projectId: 'jamiiclubapp',
    storageBucket: 'jamiiclubapp.firebasestorage.app',
    iosBundleId: 'com.jamiiclub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyeCVyyr-xm6q5YGFa6dzev6NEDQHRR5M',
    appId: '1:1007172590075:ios:035a9b5e66d7d2993ad35e',
    messagingSenderId: '1007172590075',
    projectId: 'jamiiclubapp',
    storageBucket: 'jamiiclubapp.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl6PIhPLKbJ437WADmHc44Z7nncmKGo2M',
    appId: '1:1007172590075:web:83eb4aac35165a4e3ad35e',
    messagingSenderId: '1007172590075',
    projectId: 'jamiiclubapp',
    authDomain: 'jamiiclubapp.firebaseapp.com',
    storageBucket: 'jamiiclubapp.firebasestorage.app',
    measurementId: 'G-644WK1W3LG',
  );

}